application: cpr123-enrollment-watch
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /templates/css
  static_dir: templates/css

- url: /.*
  script: class_list_grabber_gae.app


libraries:
- name: jinja2
  version: latest
